services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: "composer install && php artisan config:clear"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_ENV
        value: production
